# Generated by Django 3.1.6 on 2021-02-27 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='employers',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies')),
            ],
        ),
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.companies')),
                ('address', models.CharField(max_length=600)),
                ('established_year', models.CharField(max_length=4)),
                ('ceo', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=13)),
                ('gst_no', models.CharField(max_length=100)),
                ('company_logo', models.CharField(blank=True, max_length=300)),
                ('modified_at', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='employer_profile',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.employers')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'others')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=600)),
                ('mobile_no', models.CharField(blank=True, max_length=13)),
                ('joining_date', models.DateField()),
                ('profile_image', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('add_role', models.CharField(blank=True, max_length=300, null=True)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full_time'), ('Part Time', 'Part_time'), ('Training', 'Training')], max_length=13)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=11)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.project')),
            ],
        ),
    ]
