# Generated by Django 3.1.6 on 2021-02-28 13:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210227_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to=users.models.company_profile.nameFile),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
