# Generated by Django 3.1.6 on 2021-02-27 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('request', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject')], default='pending', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Department_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('General', 'General'), ('Annual', 'Annual'), ('Emergency', 'Emergency'), ('Special', 'Special')], default='general', max_length=10)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField(max_length=1200)),
                ('subject', models.CharField(max_length=500)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('modified_at', models.DateField(default=datetime.date.today)),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('client_name', models.CharField(max_length=300)),
                ('project_leader', models.CharField(max_length=300)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('modified_at', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=12)),
                ('salary', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
