# Generated by Django 3.1.6 on 2021-02-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies'),
        ),
        migrations.AddField(
            model_name='salary',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employers'),
        ),
        migrations.AddField(
            model_name='project',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies'),
        ),
        migrations.AddField(
            model_name='leave',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies'),
        ),
        migrations.AddField(
            model_name='leave',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employers'),
        ),
        migrations.AddField(
            model_name='department_company',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies'),
        ),
        migrations.AddField(
            model_name='department_company',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employers'),
        ),
    ]
